### ISSUE TITLE
eigenvalue API bug

### ISSUE THREAD

**Issue by astraw** [stainless-steel/lapack#12]
Hi,

I noticed that the interface to the `?geev()` methods changed from having argument such as `vl: &mut [f64]` to ` vl: &mut f64` (e.g. compare earlier commit [61d32](https://github.com/stainless-steel/lapack/blob/61d32b51c80e8408f8f9955da7087539a8f3d501/src/fortran.rs#L9005) to commit [c4daf](https://github.com/stainless-steel/lapack/blob/c4daf5b95358fba061050fe02060a91fecff1d78/src/fortran.rs#L8534) ). This seems to be a bug, as `vl` and `vr` are array inputs to these functions. I could hand-tune the `fortran.py` (and `c.py`) to fix the function calls for `?geev()` myself and submit a PR, but I don't know the reasons for switching `vl` and `vr` and worry that I may break other functions.

Note that fixing this will require bumping the version as we'll be changing the API.

**Comment by IvanUkhov** [comment]
Thank you for pointing out this! Please have a look at the two commits in #13 and confirm that the changes are adequate. Thanks again!

**Comment by astraw** [comment]
Yes, this solves the problem, thanks.

Eventually it would be good to do define the data types systematically and automatically. The netlib source code seems like it must have the required info, as their [HTML docs](http://www.netlib.org/lapack/explore-html/d3/dfb/group__real_g_eeigen_ga8e4fcdbc268d998397192b119f27da83.html#ga8e4fcdbc268d998397192b119f27da83) indicate if each argument is a scalar or array.

**Comment by IvanUkhov** [comment]
Yes, I absolutely agree with you, and it’s a nice idea about Netlib’s documentation.
