### ISSUE TITLE
Out-variables are unnecessarily slices

### ISSUE THREAD

**Issue by sfackler** [stainless-steel/lapack#16]
For example, the `iter` argument to `dsgesv` is a single integer, but the bindings here have it represented as an `&mut [i32]` rather than `&mut i32`.

**Comment by IvanUkhov** [comment]
Thanks for the issue! The functions are generated mechanically by [c.py](https://github.com/stainless-steel/lapack/blob/master/bin/c.py) and [fortran.py](https://github.com/stainless-steel/lapack/blob/master/bin/fortran.py). Both have a function called `is_scalar`, which decide whether an argument is a scalar or a slice. It uses some heuristic to this end as, in many cases, it’s not obvious from the argument’s type.

**Comment by IvanUkhov** [comment]
Fixed in #17.
