### ISSUE TITLE
-lgfortran for found on Fedora 22

### ISSUE THREAD

**Issue by 00shiv** [stainless-steel/lapack#5]
I have /usr/lib64/libgfortran.so.3 but I still get this error:
------------------------------------------------
note: /usr/bin/ld: cannot find -lgfortran
------------------------------------------------
on Fedora 22. Is this that has to be fixed as part of openblas-provider or is there something that I have to fix in my Cargo.toml?

**Comment by 00shiv** [comment]
Sorry, false alarm.

**Comment by IvanUkhov** [comment]
@00shiv, my reply [here](https://github.com/cmr/openblas-provider/issues/4) might be relevant.

Regards,
Ivan
