### ISSUE TITLE
Linking error undefined reference to `dsyev_'

### ISSUE THREAD

**Issue by k34n3** [stainless-steel/lapack#9]
................/lapack-0.8.1/src/lib.rs:8262: undefined reference to `dsyev_'

I'm just trying the example and am getting this linking error. I installed OpenBLAS from git, having it in my library path. 

Any idea?

**Comment by IvanUkhov** [comment]
The library builds its own version of OpenBLAS via [openblas-prvider](https://github.com/cmr/openblas-provider). Regarding the usage of an already installed OpenBLAS, please have a look at my answer [here](https://github.com/cmr/openblas-provider/issues/4); it might be relevant.


Regards,
Ivan

**Comment by IvanUkhov** [comment]
Let me check if I understand the situation correctly. There is no problem with compiling OpenBLAS. The problem occurs when you plug in the `lapack` package into your `mogul` project, and the problem concerns linking. Is that about right?

There are four packages involved here: `openblas-provider`, `lapack-sys`, `lapack`, and `mogul`. Let’s try to figure out where this chain breaks down. Could you please clone `lapack` and run `cargo test`? If it doesn’t work, please try doing the same with respect to `lapack-sys`. Thanks.

Regards,
Ivan

**Comment by k34n3** [comment]
# For lapack
git clone https://github.com/stainless-steel/lapack.git
Cloning into 'lapack'...
remote: Counting objects: 3454, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 3454 (delta 4), reused 1 (delta 1), pack-reused 3444
Receiving objects: 100% (3454/3454), 1.78 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2819/2819), done.
Checking connectivity... done.
[keane@linarcher test]$ cargo test
Could not find `Cargo.toml` in `/home/keane/dev/rust/test` or any parent directory
[keane@linarcher test]$ ls
lapack
[keane@linarcher test]$ cd lapack/
[keane@linarcher lapack]$ ls
Cargo.toml  generate.py  LICENSE.txt  README.md  src
[keane@linarcher lapack]$ cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling openblas-provider v0.1.7
   Compiling libc v0.2.2
   Compiling num v0.1.27
   Compiling lapack-sys v0.4.1
   Compiling lapack v0.8.1 (file:///home/keane/dev/rust/test/lapack)
     Running target/debug/lapack-09e419a9326dde6f

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests lapack

running 1 test
test _0 ... FAILED

failures:

---- _0 stdout ----
        <anon>:8:9: 8:18 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
<anon>:8     let mut lwork = 4 * n as isize;
                 ^~~~~~~~~
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/rustdoctest.jz5fNyaKfyht/rust_out.0.o" "-o" "/tmp/rustdoctest.jz5fNyaKfyht/rust_out" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "/home/keane/dev/rust/test/lapack/target/debug/liblapack.rlib" "/home/keane/dev/rust/test/lapack/target/debug/deps/liblapack_sys-19ab80725ca3c83e.rlib" "/home/keane/dev/rust/test/lapack/target/debug/deps/liblibc-540159808ccfa9ab.rlib" "/home/keane/dev/rust/test/lapack/target/debug/deps/libopenblas_provider-601a7b1eda73c46c.rlib" "/home/keane/dev/rust/test/lapack/target/debug/deps/libnum-397f282c1d72fe58.rlib" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-1bf6e69c" "-L" "/home/keane/dev/rust/test/lapack/target/debug/deps" "-L" "/home/keane/dev/rust/test/lapack/target/debug" "-L" "/home/keane/dev/rust/test/lapack/target/debug/build/openblas-provider-601a7b1eda73c46c/out/opt/OpenBLAS/lib" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/keane/dev/rust/test/lapack/.rust/lib/x86_64-unknown-linux-gnu" "-L" "/home/keane/dev/rust/test/lapack/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-l" "gfortran" "-l" "openblas" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "rt" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: /tmp/rustdoctest.jz5fNyaKfyht/rust_out.0.o: In function `dsyev::he350252389f77f23Ehs':
rust_out.0.rs:(.text._ZN5dsyev20he350252389f77f23EhsE+0x26b): undefined reference to `dsyev_'
collect2: error: ld returned 1 exit status

error: aborting due to previous error


failures:
    _0

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured


# For lapack-sys
[keane@linarcher lapack-sys]$ cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling openblas-provider v0.1.7
   Compiling libc v0.2.2
   Compiling lapack-sys v0.4.1 (file:///home/keane/dev/rust/test/lapack-sys)
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/keane/dev/rust/test/lapack-sys/target/debug/lib-b85ad63e31dfc28f.0.o" "-o" "/home/keane/dev/rust/test/lapack-sys/target/debug/lib-b85ad63e31dfc28f" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserialize-1bf6e69c.rlib" "/home/keane/dev/rust/test/lapack-sys/target/debug/liblapack_sys.rlib" "/home/keane/dev/rust/test/lapack-sys/target/debug/deps/liblibc-540159808ccfa9ab.rlib" "/home/keane/dev/rust/test/lapack-sys/target/debug/deps/libopenblas_provider-601a7b1eda73c46c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1bf6e69c.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1bf6e69c.rlib" "-L" "/home/keane/dev/rust/test/lapack-sys/target/debug" "-L" "/home/keane/dev/rust/test/lapack-sys/target/debug/deps" "-L" "/home/keane/dev/rust/test/lapack-sys/target/debug/build/openblas-provider-601a7b1eda73c46c/out/opt/OpenBLAS/lib" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/keane/dev/rust/test/lapack-sys/.rust/lib/x86_64-unknown-linux-gnu" "-L" "/home/keane/dev/rust/test/lapack-sys/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-l" "gfortran" "-l" "openblas" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "rt" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: /home/keane/dev/rust/test/lapack-sys/target/debug/lib-b85ad63e31dfc28f.0.o: In function `lib::link':
/home/keane/dev/rust/test/lapack-sys/tests/lib.rs:16: undefined reference to `dsyev_'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `lapack-sys`.

To learn more, run the command again with --verbose.

**Comment by IvanUkhov** [comment]
Let’s see if it’s OpenBLAS to blame by switching to Netlib:

```
git clone https://github.com/stainless-steel/lapack-sys.git
cd lapack-sys
cargo test --no-default-features --features=netlib
```

The Netlib provider requires cmake.

**Comment by k34n3** [comment]
Yes, compiles and tests correctly. Then I went back, removed gfortran, reinstalled it. Magically *everything* now.
